### ISSUE TITLE
Maybe something error in api/train.py?

### ISSUE THREAD

**Issue by Senwang98** [yzd-v/MGD#1]
Hi, @yzd-v 
I am trying to train your released code about MGD.
I am familiar with your FGD code, so I think it is easy tu run MGD too.

When I train retinanet, error happen! I use mmcv-full==1.4.0 and mmdet==2.17.0.
![image](https://user-images.githubusercontent.com/23122139/172005031-ee41f23c-dbac-46ad-880a-1f46de2e2548.png)
It seems that mmdet do not support `runner_type`.

I am not sure this is something error, so I ask you for some help.
After comment this line, the code is ok to train. (The default mode is `EpochBasedRunner`)

Thanks for you nice work and wish for your reply!

**Comment by yzd-v** [comment]
Thank you for this. I wrote the wrong mmdet version in README. This repo uses mmdet==2.19.0 actually.

**Comment by Senwang98** [comment]
@yzd-v 
Fine
