### ISSUE TITLE
The reproduced results for semantic segmentation

### ISSUE THREAD

**Issue by Debrove** [yzd-v/MGD#13]
Hi, Thanks for your work!

I reproduced the results by `psp_r101_distill_psp_r18_40k_512x512_city.py`. I got 74.95 mIoU without any modification on the config file. Moreover, I set use_logit = False and obtained 73.46 mIoU.

Two questions are below:
1. Are the reported results of 74.10 and 73.63 in the paper on val set or test set？
2. In Table 4, the input size of the student is 512x512, while in Section 4.3, the input size is 512x1024. Is this a typo?

It is appreciated if you can help me! Thank you!

**Comment by yzd-v** [comment]
1. val
2. The size should be 512x512. I'm sorry about this typo.
