### ISSUE TITLE
Question about generative block

### ISSUE THREAD

**Issue by pzn666** [yzd-v/MGD#14]
Thanks for your great work! I have some questions about the generative block (sec. 5.4). Did you keep the generative block simple on purpose? What do you think if we use more complex modules as generative blocks (such as GcBlock in FGD)? Thanks!

**Comment by yzd-v** [comment]
We utilize a simple block for generation so that the student needs stronger semantic infromation to generate teacher's feature with such block. A more complex block may help the student to generate teacher's feature easily, causing the student gets weaker semantic information than simpler block.

**Comment by pzn666** [comment]
Thanks!
