### ISSUE TITLE
Some confusion about the semantic segmentation in MGD

### ISSUE THREAD

**Issue by sscckk** [yzd-v/MGD#15]
Hi, Thank you for your interesting work!
I have encountered some confusion and seek your help.

1. In your paper, the teacher PspNet-Res101 is trained for 80k iterations, while in the code a 40k pre-trained model is used, so is it a typo in the paper?

2. I refer to your training log "PspR18_TPspR101_73.73.log". It doesn't seem to match the config file “psp_r101_distill_psp_r18_40k_512x512_city.py”, and there is no module like “neck_fpn_convs" found in pspnet. So, in the semantic segmentation task, which features are actually distilled?
![image](https://user-images.githubusercontent.com/46714152/222037418-f1f4284e-143d-4e84-88a2-77d023459879.png)

Looking forward to your reply.
Thank you agian!

**Comment by yzd-v** [comment]
1. I'm sorry about this typo. Please follow the code.
2. The name doesn't matter. It uses FGD's code at first. So such name appear in the log. For seg, distilling on the last feature is enough.
![image](https://user-images.githubusercontent.com/54797851/222065303-8f83a414-e503-4577-ae2a-28cf207ef68b.png)
