### ISSUE TITLE
About the generative block

### ISSUE THREAD

**Issue by sscckk** [yzd-v/MGD#16]
Thanks for your work.

I'm so curious why the generative block is just a simple stack of 3x3 Conv.

In addition, a convolution is usually followed by a BatchNorm module. But the generative block in your paper does not use any BatchNorm, what is the reason for this?

Looking forward to your reply!
Thank you~

**Comment by yzd-v** [comment]
The power of student's feature is so strong that a simple generative block can generate teacher's feature.

**Comment by Golden-Ele** [comment]
你好，我正在研究你关于MGD中生成块的作用，目前还是无法理解为什么两个3x3卷积就可以生成教师网络的特征，您能详细解释一下吗？
