### ISSUE TITLE
mask率与生成块

### ISSUE THREAD

**Issue by KeepOn2023** [yzd-v/MGD#17]
您好，我尝试设置mask=0，并使用3x3Conv-ReLU-3x3Conv生成块进行蒸馏，似乎最终的精度并没有降低，和mask=0.5相当。
所以，我有些疑惑，mask在蒸馏中发挥了什么作用呢？是否可以认为精度提升主要依靠生成块呢？
还有，您在Fig5中mask=0情况下得到精度71.41%，请问这里的设置是什么呢？这里使用生成块了吗？
期待您的回复！谢谢

**Comment by yzd-v** [comment]
也达到了71.58%吗？71.41%的结果和你使用的设置是一样的，resnet18的训练结果不是很稳定，会有一些误差。mask的作用是人为的去减弱学生的特征强度，相当于一种aug，由此训练的学生的特征的表达能力能更强。是使用了生成模块的

**Comment by KeepOn2023** [comment]
是的，甚至还超过了。
我在原有代码上得到的Top-1精度是71.72%（channel mask）
当设置mask=0，也就是使用`new_fea = self.generation(preds_S)`，在第91 epoch时，得到的Top-1精度就已经到了71.74%
所以才会疑惑，理论上mask的存在会使得学生特征的表达能力能更强，但是在精度上却表现出相反的结果

**Comment by yzd-v** [comment]
会有一些结果的波动，然后当时我是在空间维度做的实验，channel确实对分类会好一些

**Comment by KeepOn2023** [comment]
谢谢您的回复
在mask=0的时候，channel和空间是没有区别的，所以这里的精度71.74%确实是比mask＞0的时候要好
不过话说后来，波动是客观有点，只是比预想的要更大
