### ISSUE TITLE
how to get the distill loss weight

### ISSUE THREAD

**Issue by kenwangchao** [yzd-v/MGD#2]
In the paper, it adopt 2x10（-5）as loss weights for detection, so before apply the weights, what is the correct MGD loss value? As for me, the loss value of MGD without loss weight is around 5 in initial, if i multiply with the wights, it will be a very small number...

**Comment by yzd-v** [comment]
You can change the hyper-parameter to make the value of MGD loss similar to that of the original loss. You can refer the MGD/original loss in the log.
