### ISSUE TITLE
About the student loss

### ISSUE THREAD

**Issue by myt889** [yzd-v/MGD#6]
Hi, thank you for your nice work.
      I am not familiar with Knowledge Distilling，so I can't not understance what “the original loss” in paper  refers to. For example, it means  classification loss for classification task of student model, right?  hope that you can give me some guidence.
![image](https://user-images.githubusercontent.com/77277761/186877013-e5802758-692a-4f63-bad0-129984a99767.png)

**Comment by yzd-v** [comment]
Yes, it's the original loss for the original task without distillation.
