### ISSUE TITLE
About the student network

### ISSUE THREAD

**Issue by myt889** [yzd-v/MGD#7]
Hi, I still have two questions as follow: (1) I can't know find out the detail design of the student network, including the Masked operation and the generation, since I do not use the MMClassification. (2) As I know, when test on test dataset, only the student network including the masked feature module and the Generation module can be used for test, right?

**Comment by yzd-v** [comment]
1) The implementation of MGD is in [mgd.py](https://github.com/yzd-v/MGD/blob/master/cls/mmcls/distillation/losses/mgd.py). 2) For inferencing, only the student network is used. Distillation won't introduce any extra parameters or time cost.  I suggest you may read more papers and codebase about distillation. These are really basic issue for distillation.

**Comment by myt889** [comment]
> 1. The implementation of MGD is in [mgd.py](https://github.com/yzd-v/MGD/blob/master/cls/mmcls/distillation/losses/mgd.py). 2) For inferencing, only the student network is used. Distillation won't introduce any extra parameters or time cost.  I suggest you may read more papers and codebase about distillation. These are really basic issue for distillation.

Thank you so much, I get it.
