### ISSUE TITLE
About Experiment Details

### ISSUE THREAD

**Issue by saintrealchoi** [yzd-v/MGD#8]
First of all, Thank you for your awesome works!

I was very impressed by your work. So, I reproduce it by `config/mgd/retina_rx101_64x4d_distill_retina_r50_fpn_2x_coco.py`
Actually, I got **41.4 mAP on batchsize=16** (samples_per_gpu=8 on A5000 * 2) and lower mAP than Paper on batchsize=32 (samples_per_gpu=16 on A6000 * 2).
It's strange that there are very different results depending on the batch size.
Can you tell me about your experiment detail?

Sincerely,

**Comment by yzd-v** [comment]
The paper follows the training setting of the baseline model, which uses 2 sample * 8 GPUs.  So the batchsize in the paper is 16 and the final mAP is 41.0. The training log can be seen in [README](https://github.com/yzd-v/MGD/tree/master/det). So you reproduce a higher result than the paper in fact.

**Comment by yzd-v** [comment]
Oh, I just check this. The teacher in config/mgd/retina_rx101_64x4d_distill_retina_r50_fpn_2x_coco.py is Retina-RX101 with 3x training time. To keep the same with FGD, the teacher in the paper is Retina-RX101 with 1x training time. The stronger teacher benefits the student more.

**Comment by saintrealchoi** [comment]
Oh, I see!
https://github.com/yzd-v/MGD/blob/708bca04acc611ae6a92af34281aca4556d6c398/det/configs/distillers/mgd/retina_rx101_64x4d_distill_retina_r50_fpn_2x_coco.py#L10
should be changed to 
https://github.com/yzd-v/FGD/blob/c03a6cf3b3cb3cbfd5554dbf4766e7135747d22d/configs/distillers/fgd/fgd_retina_rx101_64x4d_distill_retina_r50_fpn_2x_coco.py#L14

**Comment by saintrealchoi** [comment]
Thank you for your reply! :)

**Comment by yzd-v** [comment]
Yes, you can get the results in the paper with this teacher. Besides, FGD can get better results with a stronger teacher too.
