### ISSUE TITLE
About Distillation Loss

### ISSUE THREAD

**Issue by saintrealchoi** [yzd-v/MGD#9]
I have another question, so I'm leaving an issue like this.

![Screenshot from 2022-09-13 11-24-02](https://user-images.githubusercontent.com/45679609/189793460-3f78043c-7ab7-4220-8368-bff2c9d475bb.png)

Upper graph is distillation loss `loss_mgd_fpn_*` graph. ( blue one is with random mask, red is without random mask)
I wonder that With random mask distillation loss is higher than Without it. but, with Random mask mAP(metric) is higher than without it. (w/ 41.4 -> w/o 41.3)
if proposed loss is working well, loss should be lower than without random mask.

can you explain about it? I'd appreciate it if you could recommend some materials for reference.

Sincerely,

**Comment by yzd-v** [comment]
When using random mask, we force student's feature to generate teacher's feature from 0 value. For w/o random mask, we force student's feature to generate teacher's feature from student's original feature, which is much easier. So the distillation loss is lower than with random mask. As for mAP, what we want to claim in the paper is with random mask is better for distillation.

**Comment by saintrealchoi** [comment]
Thank you for your Reply :)
